<h3>
    <?php echo $this->translate('File Storage');?>
</h3>
<?php if (count($this->paginator)): ?>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12 conteudo">
                <div class="dados">

                    <table class="table table-striped table-bordered" id="dados">
                        <thead>
                            <tr>
                                <th class="span1">ID</th>
                                <th class="span4"><?php echo $this->translate('Name');?></th>
                                <th class="span4"><?php echo $this->translate('Download');?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->paginator as $document): ?>
                                <tr>
                                    <td><?php echo $document->getId(); ?></td>
                                    <td><?php echo $document->getName(); ?></td>
                                    <td>
                                        <a target="_blank" href="<?php
                                        echo $document->getDownloadLink();
                                        ?>">
                                            <?php echo $this->translate('Download');?></a> | 
                                        <a return="confirm('<?php echo $this->translate('This action can\'t be reversed');?>')" href="<?php
                                           echo $this->url('file-storage/delete', array(
                                               'id' => $document->getId(),
                                           ));
                                           ?>">
                                        <?php echo $this->translate('Remove');?>                                        
                                        </a>
                                    </td>
                                </tr>
    <?php endforeach; ?>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>

    <a href="<?php echo $this->url('file-storage/create'); ?>" class="btn-primary btn">
    <?php echo $this->translate('Add new');?>
    </a>
<?php endif; ?>
