<?php
$form = $this->form;

$form->setAttribute(
    'action',
    $this->url(
        'document',
        array(
            'controller'=>'document', 
            'action' => 'create'
        )
    )
); 

$form->prepare();
?>

<div class="well">
    <?php echo $this->form()->openTag($form); ?>

    <div class="row-fluid">
        <div class="span4">
            <?php echo $this->formRow($form->get('content')); ?>
        </div>
    </div>
</div>      

<div class="form-actions">
    <?php echo $this->formSubmit($form->get('submit')); ?>
</div>       
<?php echo $this->formRow($form->get('id')); ?>
<?php echo $this->form()->closeTag(); ?>
